server:
  port: 8081
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/bolo?serverTimezone=UTC%2B8&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
    username: root
    password: '000000'
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000 # 单位ms
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 12
      minimum-idle: 10
      pool-name: VHikariPool

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
minio:
  endpoint: http://localhost:9000
  access-key: VknoEcIw2sKsegMtLyvy
  secret-key: PydBE5kjhjouXOTEmCQBpmogPq0qyQR6JtlaQgBi
  bucket-name: bolo

knife4j:
  enable: false # 关闭增强功能
